name: CI/CD

on: 
  push:
    branches:
      - main

env:
  EKS_CLUSTER_NAME: starcar-cluster
  AWS_REGION: us-east-2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: docker compose -f docker-compose.prod.yml build

      - name: Tag images
        run: |
          docker tag pateichler/starcar-backend:latest pateichler/starcar-backend:${{ github.sha }}
          docker tag pateichler/starcar-frontend:latest pateichler/starcar-frontend:${{ github.sha }}

      - name: Push images
        run: |
          docker push pateichler/starcar-backend:latest
          docker push pateichler/starcar-backend:${{ github.sha }}
          docker push pateichler/starcar-frontend:latest
          docker push pateichler/starcar-frontend:${{ github.sha }}

  deploy:
    name: Deploy
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure AWS credientals
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Kubernetes context
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy images
        run: |
          kubectl set image deployment/starcar-backend -n starcar starcar-backend=pateichler/starcar-backend:${{ github.sha }}
          kubectl set image deployment/starcar-frontend -n starcar starcar-frontend=pateichler/starcar-frontend:${{ github.sha }}
